import turtle

turtle.bgcolor("dodger blue")

scn = turtle.Screen()
Aaron = turtle.Turtle()
Bob = turtle.Turtle()
Calvin = turtle.Turtle()

#grass
Aaron.color("forest green")
Aaron.speed(.5)
Aaron.begin_fill()
Aaron.forward(800)
Aaron.right(90)
Aaron.forward(800)
Aaron.right(90)
Aaron.forward(1600)
Aaron.right(90)
Aaron.forward(800)
Aaron.right(90)
Aaron.forward(800)
Aaron.end_fill()

#trees
Bob.forward(300)
Bob.left(180)
Bob.forward(40)
Bob.right(90)
Bob.color("brown")
Bob.begin_fill()
Bob.forward(80)
Bob.left(90)
Bob.forward(10)
Bob.left(90)
Bob.forward(80)
Bob.end_fill()
Bob.right(180)
Bob.forward(80)
Bob.color("forest green")
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.right(90)
Bob.forward(5)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.forward(5)
Bob.right(90)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.color("brown")
Bob.forward(80)
Bob.right(90)
Bob.color("forest green")
Bob.forward(100)

Bob.right(90)
Bob.color("brown")
Bob.begin_fill()
Bob.forward(80)
Bob.left(90)
Bob.forward(10)
Bob.left(90)
Bob.forward(80)
Bob.end_fill()
Bob.right(180)
Bob.forward(80)
Bob.color("dark green")
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.right(90)
Bob.forward(5)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.forward(5)
Bob.right(90)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.color("brown")
Bob.forward(80)
Bob.right(90)
Bob.color("forest green")
Bob.forward(100)

Bob.right(90)
Bob.color("brown")
Bob.begin_fill()
Bob.forward(80)
Bob.left(90)
Bob.forward(10)
Bob.left(90)
Bob.forward(80)
Bob.end_fill()
Bob.right(180)
Bob.forward(80)
Bob.color("forest green")
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.right(90)
Bob.forward(5)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.forward(5)
Bob.right(90)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.color("brown")
Bob.forward(80)
Bob.right(90)
Bob.color("forest green")
Bob.forward(100)

Bob.right(90)
Bob.color("brown")
Bob.begin_fill()
Bob.forward(80)
Bob.left(90)
Bob.forward(10)
Bob.left(90)
Bob.forward(80)
Bob.end_fill()
Bob.right(180)
Bob.forward(80)
Bob.color("dark green")
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.right(90)
Bob.forward(5)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.forward(5)
Bob.right(90)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.color("brown")
Bob.forward(80)
Bob.right(90)
Bob.color("forest green")
Bob.forward(100)

Bob.right(90)
Bob.color("brown")
Bob.begin_fill()
Bob.forward(80)
Bob.left(90)
Bob.forward(10)
Bob.left(90)
Bob.forward(80)
Bob.end_fill()
Bob.right(180)
Bob.forward(80)
Bob.color("dark green")
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.right(90)
Bob.forward(5)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.forward(5)
Bob.right(90)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.color("brown")
Bob.forward(80)
Bob.right(90)
Bob.color("forest green")
Bob.forward(100)

Bob.right(90)
Bob.color("brown")
Bob.begin_fill()
Bob.forward(80)
Bob.left(90)
Bob.forward(10)
Bob.left(90)
Bob.forward(80)
Bob.end_fill()
Bob.right(180)
Bob.forward(80)
Bob.color("dark green")
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.right(90)
Bob.forward(5)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.forward(5)
Bob.right(90)
Bob.begin_fill()
Bob.circle(20)
Bob.end_fill()
Bob.color("brown")
Bob.forward(80)
Bob.right(90)
Bob.color("forest green")
Bob.forward(100)

turtle.exitonclick()

